version: "3.8"

volumes:
  vol-emqx-data:            ##DATOS DE LOGUEO Y REGLAS
    name: foo-emqx-data
#  vol-emqx-etc:             ##CONFIGURACION DE EMQX -
#    name: foo-emqx-etc
  vol-emqx-log:             ##ARCHIVOS DE LOG
    name: foo-emqx-log


services:

  mongodb:
    image: mongo:6.0
    restart: always
    environment:
      TZ: "${TZ}"
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpassword
    volumes:
      - ./mongodata:/data/db
    ports:
      - '27017:27017'
  
  
  emqx:
    image: emqx/emqx:4.4.14
    restart: always
    ports:
      - '18083:18083'      ##puerto por donde entro al dashboard emqx
      - '1883:1883'
      - '8883:8883'
      - '8083:8083'
      - '8085:8081'

    volumes:
     - vol-emqx-data:/opt/emqx/data
    #  - vol-emqx-etc:/opt/emqx/etc
     - vol-emqx-log:/opt/emqx/log

    links:
      - mongodb

    extra_hosts:
     - "localhost:172.21.112.1"

    depends_on:
     - mongodb

    environment:
      EMQX_NAME: confiplant-gl
      EMQX_HOST: 127.0.0.1
      TZ: "${TZ}"

      #DEFAULT DASH PASS
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: ${EMQX_DEFAULT_USER_PASSWORD}

      #DEFAULT APP SECRET
      EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: ${EMQX_DEFAULT_APPLICATION_SECRET}
      
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_NOMATCH: "deny"

      #MONGO CONNECTION
      EMQX_AUTH__MONGO__TYPE: single
      EMQX_AUTH__MONGO__TOPOLOGY__POOL_SIZE: 1
      EMQX_AUTH__MONGO__TOPOLOGY__MAX_OVERFLOW: 0
      
      EMQX_AUTH__MONGO__SERVER: "mongo:${MONGO_EXT_PORT}"
      EMQX_AUTH__MONGO__POOL: 8

      EMQX_AUTH__MONGO__LOGIN: "${MONGO_USERNAME}"
      EMQX_AUTH__MONGO__PASSWORD: "${MONGO_PASSWORD}"
      EMQX_AUTH__MONGO__AUTH_SOURCE: admin

      EMQX_AUTH__MONGO__DATABASE: "CP_DB"
      EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxauthrules"
      
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
      EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"

      EMQX_AUTH__MONGO__SUPER_QUERY: "off"

      ##Enable ACL query
      EMQX_AUTH__MONGO__ACL_QUERY: "on"
      EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: "username=%u"

      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_managment,emqx_dashboard,emqx_auth_mongo"



      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000