version: "3.8"

volumes:
  vol-emqx-data: ##DATOS DE LOGUEO Y REGLAS
    name: foo-emqx-data
  vol-emqx-etc: ##CONFIGURACION DE EMQX -
    name: foo-emqx-etc
#  vol-emqx-log:             ##ARCHIVOS DE LOG
#    name: foo-emqx-log

services:
  backend:
    container_name: nodesv
    restart: always
    build: ./be
    env_file:
      - ./be/.env
    ports:
      - "3002:3001"
    links:
      - mongo
      - emqx
    depends_on:
      - mongo
      - emqx

  mongo:
    container_name: mongo
    image: mongo:5.0.18
    restart: always
    environment:
      TZ: "${TZ}"
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongodata:/data/db
    ports:
      - "${MONGO_EXT_PORT}:27017"

  emqx:
    container_name: emqx
    image: emqx/emqx:4.4.18
    ports:
      - "18083:18083" ##puerto por donde entro al dashboard emqx   ssl 18083:18083 http
      - "1883:1883"
      - "8883:8883" # tcp  1883:1883 tcp
      - "8083:8083" # tcp ssl 8883:1883 tcp
      - "8085:8081"

    volumes:
      - vol-emqx-data:/opt/emqx/data
      - /certs:/opt/emqx/etc/certs
      - vol-emqx-etc:/opt/emqx/etc
    # - vol-emqx-log:/opt/emqx/log

    links:
      - mongo
    depends_on:
      - mongo

    environment:
      EMQX_NAME: confiplant-gl
      EMQX_HOST: 127.0.0.1
      TZ: "${TZ}"

      #DEFAULT DASH PASS
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: ${EMQX_DEFAULT_USER_PASSWORD}

      #DEFAULT APP SECRET
      EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: ${EMQX_DEFAULT_APPLICATION_SECRET}

      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_NOMATCH: "deny"

      #MONGO CONNECTION
      EMQX_AUTH__MONGO__TYPE: single
      EMQX_AUTH__MONGO__TOPOLOGY__POOL_SIZE: 1
      EMQX_AUTH__MONGO__TOPOLOGY__MAX_OVERFLOW: 0

      EMQX_AUTH__MONGO__SERVER: "mongo:${MONGO_EXT_PORT}"
      EMQX_AUTH__MONGO__POOL: 8

      EMQX_AUTH__MONGO__LOGIN: "${MONGO_USERNAME}"
      EMQX_AUTH__MONGO__PASSWORD: "${MONGO_PASSWORD}"
      EMQX_AUTH__MONGO__AUTH_SOURCE: admin

      EMQX_AUTH__MONGO__DATABASE: "CP_DB"
      EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxauthrules"

      EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
      EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
      EMQX_AUTH__MONGO__SUPER_QUERY: "off"

      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
      EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"

      ##Enable ACL query
      EMQX_AUTH__MONGO__ACL_QUERY: "on"
      EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: "username=%u"

      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_managment,emqx_auth_mongo,emqx_dashboard"

      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000

      #CERTIFICADOS

      #CERTIFICADOS
      EMQX_LISTENER__SSL__EXTERNAL__KEYFILE: "opt/etc/certs/emqx.key"
      EMQX_LISTENER__SSL__EXTERNAL__CERTFILE: "opt/etc/certs/emqx.pem"
      EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE: "opt/etc/certs/ca.pem"

      EMQX_LISTENER__WSS__EXTERNAL__KEYFILE: "opt/etc/certs/emqx.key"
      EMQX_LISTENER__WSS__EXTERNAL__CERTFILE: "opt/etc/certs/emqx.pem"
      EMQX_LISTENER__WSS__EXTERNAL__CACERTFILE: "opt/etc/certs/ca.pem"
